#配置dubbo消费者
spring:
  dubbo:
    application:
      name: springboot-dubbo-consumer
    registry:
      address: zookeeper://127.0.0.1:2181
    scan: cn.tang.demo
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  redis:
    host: 47.94.224.238
    port: 6379
#    password: redis
    jedis:
      pool:
        max-active: 30
        max-wait: -1ms
        max-idle: 30
        min-idle: 0

#如果使用外置tomcat，下面不用设置
#server:
#  port: 9891
#  servlet:
#    context-path: /demo-web
#  tomcat:
#    uri-encoding: UTF-8
